import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { useLocation } from "wouter";
import { useGetMe, type User } from "@workspace/api-client-react";

interface AuthContextType {
  user: User | null;
  isLoading: boolean;
  logout: () => void;
  setToken: (token: string) => void;
}

const AuthContext = createContext<AuthContextType | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [token, setTokenState] = useState<string | null>(localStorage.getItem("habit_token"));
  const [, setLocation] = useLocation();

  // Override fetch globally to inject the token into ALL requests generated by Orval
  useEffect(() => {
    const originalFetch = window.fetch;
    window.fetch = async (...args) => {
      const currentToken = localStorage.getItem("habit_token");
      if (currentToken) {
        const [resource, config] = args;
        if (config) {
          config.headers = {
            ...config.headers,
            Authorization: `Bearer ${currentToken}`,
          };
        } else {
          args[1] = {
            headers: { Authorization: `Bearer ${currentToken}` },
          };
        }
      }
      return originalFetch(...args);
    };
    return () => {
      window.fetch = originalFetch;
    };
  }, []);

  const setToken = (newToken: string) => {
    localStorage.setItem("habit_token", newToken);
    setTokenState(newToken);
  };

  const logout = () => {
    localStorage.removeItem("habit_token");
    setTokenState(null);
    setLocation("/login");
  };

  const { data: user, isLoading, error } = useGetMe({
    query: {
      retry: false,
      enabled: !!token,
    }
  });

  useEffect(() => {
    if (error) {
      logout();
    }
  }, [error]);

  return (
    <AuthContext.Provider value={{ user: user ?? null, isLoading, logout, setToken }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) throw new Error("useAuth must be used within an AuthProvider");
  return context;
}
